### ISSUE TITLE
Inspection dump tab causes 500 on production

### ISSUE THREAD

**Issue by gzumba** [patchlevel/event-sourcing-admin-bundle#16]
There is dump call in the inspection dump tab (duh), which does not work in production, as the dump() is not available:
https://github.com/patchlevel/event-sourcing-admin-bundle/blob/c7be5f06a6d889ee079308400a1c957d57fb3844/templates/inspection/show.html.twig#L98-L100

In recent Twig versions you could check for the function, but other than that I don't have anything clever in my mind on how to solve it.

**Comment by DanielBadura** [comment]
Hi thanks for reporting this. IIRC we designed this bundle to be a dev tool, so we did never considered it to be run in prod with prod deps. Thinking about it, it should be fine to run this also in production. Just be sure it's not public available. I think we should add this to the docs.

Checking if the dump function is there seems like a sufficient solution to prevent the error.

**Comment by DanielBadura** [comment]
Well, i just check it and it is not as easy as checking for the `dump` function. Twig itself is providing the `dump` function using `var_dump` internally. The `symfony/twig-bridge` is then overwriting this function with the `VarDumper` version. This means the `dump` function is always there. Need to think more about this.

**Comment by DanielBadura** [comment]
I decided to create a extra dump extension for our purpose. This would decouple us from the way symfony is registering the dump extension on their side.

**Comment by DanielBadura** [comment]
Is now released as https://github.com/patchlevel/event-sourcing-admin-bundle/releases/tag/1.0.0-alpha5
